aws_region = "us-west-2"
enable_control_tower = true
master_account_email = "sindhusneha@gmail.com"
master_account_id = "307946662628"
dev_account_email = "soundari1129@gmail.com"
prod_account_email = "naveenmvm14@gmail.com"
shared_account_email = "kharthie2@gmail.com"
security_account_email = "mathanram235@gmail.com"
audit_account_email = "fa0227649@gmail.com"
aft_logs_bucket_name = "aft-logs-bucket-307946662628"
organizational_units = ["Security", "Audit Log", "Sandbox"]